### ISSUE TITLE
SPD,Touch,AIR標題顏色文字修改

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#11]
SPD不要是黑色,改成藍色?
Touch及AIR也不要是黑色,改成紅色?
T1234改成TOUCH(1~4)
![93467](https://github.com/tonyghchen/621/assets/74387608/501efbe6-2a63-4b45-9ac1-0bdea0a15e27)

**Comment by tonyghchen** [comment]
Solved at 10/30 reversion
