### ISSUE TITLE
"汽缸設定"畫面修改

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#13]
1.加入標題"汽缸設定"
2.加入"全部汽缸ON"按鈕
3.加入"全部汽缸OFF"按鈕
4>定義汽缸設定命令(UART)
![t12](https://github.com/tonyghchen/621/assets/74387608/c615373d-c11d-48d2-9c08-0672e1762924)
![t13](https://github.com/tonyghchen/621/assets/74387608/7dad4de1-b067-46da-a0b0-63b02176bb93)

**Comment by tonyghchen** [comment]
Solved at 2023/10/30 reversion
