### ISSUE TITLE
定義各按鍵的UART命令(ARM to Raspberry pi)

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#16]
按鍵有:
1.鍵盤鎖住(Key Lock)ON-----螢幕岀現"鍵盤鎖住",並且不允許任何輸入(PC鍵盤,滑鼠及觸控螢幕)及機上操作盒+Y,-Y,+A,-A,AHome
2.鍵盤鎖住(Key Lock)OFF
3.原點
4.啟動生產
5.測試
6.停機
7.重置(RESET)
8.鍵盤切換(Switch)ON---螢幕岀現"鍵盤切換(",並且不允許任何輸入(PC鍵盤,滑鼠及觸控螢幕),只允許機上操作盒+Y,-Y,+A,-A,AHome
9..鍵盤切換(Switch)OFF
10.+Y (+F)
11.-Y (-F)
12.+A (+RW)
13-A (-RW)
14.AHome
![93579](https://github.com/tonyghchen/621/assets/74387608/471b4049-0938-4a69-8726-878dda8015b3)
![93578](https://github.com/tonyghchen/621/assets/74387608/75fd3662-c335-4f6c-9b33-0a0a066f9508)

**Comment by fun2781** [comment]
![93633](https://github.com/tonyghchen/621/assets/74387608/84a2d61c-7754-41ca-b4eb-4ff29c5be6ed)
![93632](https://github.com/tonyghchen/621/assets/74387608/8648b0f9-acae-438e-9155-a6bac57fdfb5)

**Comment by tonyghchen** [comment]
Keyboard Read 0x55 0x01 鍵盤鎖住 (Key Lock)ON-----螢幕岀現"鍵盤鎖住",並且不允許任何輸入(PC鍵盤,滑鼠及觸控螢幕)及機上操作盒+Y,-Y,+A,-A,Ahome
 Read 0x55 0x02 鍵盤鎖住(Key Lock)OFF
 Read 0x55 0x03 原點
 Read 0x55 0x04 啟動生產
 Read 0x55 0x05 測試
 Read 0x55 0x06 停機
 Read 0x55 0x07 重置(RESET)
 Read 0x55 0x08 鍵盤切換(Switch)ON---螢幕岀現"鍵盤切換(",並且不允許任何輸入(PC鍵盤,滑鼠及觸控螢幕),只允許機上操作盒+Y,-Y,+A,-A,AHome
 Read 0x55 0x09 鍵盤切換(Switch)OFF
 Read 0x55 0x0A +Y (+F)
 Read 0x55 0x0B -Y (-F)
 Read 0x55 0x0C +A (+RW)
 Read 0x55 0x0D -A (-RW)
 Read 0x55 0x0E A Home
