### ISSUE TITLE
加減速的計算?

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#24]
生產速率設40%,第一張圖是X1加減速設0的Action Table,第二張圖是X1加減速設100ms的Action Table,,如何計算得到?
![93923](https://github.com/tonyghchen/621/assets/74387608/38696f68-62bc-456c-a462-57fa8aec8f13)
![93924](https://github.com/tonyghchen/621/assets/74387608/dc6c86dd-a09e-47f1-8cd3-400f57f6a43f)

**Comment by tonyghchen** [comment]
Solved at 11/20 reversion
