### ISSUE TITLE
修改Touch及AIR的欄位

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#4]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w=
![t3](https://github.com/tonyghchen/621/assets/74387608/e3752408-9846-482e-9f96-015fd3698f23)
"urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 12">
<meta name=Originator content="Microsoft Word 12">
<link rel=File-List
href="file:///C:\Users\Huang\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<link rel=themeData
href="file:///C:\Users\Huang\AppData\Local\Temp\msohtmlclip1\01\clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:\Users\Huang\AppData\Local\Temp\msohtmlclip1\01\clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-TW style='tab-interval:24.0pt;text-justify-trim:punctuation'>

<p class=MsoNormal><span style='font-family:"新細明體","serif";mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:新細明體;
mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin'>原來</span><span lang=EN-US> 6</span><span style='font-family:"新細明體","serif";
mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:
新細明體;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:Calibri;
mso-hansi-theme-font:minor-latin'>行</span></p>

T1 | T2
-- | --
T3 | T4
AIR1   AIR3 | AIR2   AIR4
AIR5 | AIR6
AIR7 | AIR8

</body>

</html>

**Comment by fun2781** [comment]
![t3](https://github.com/tonyghchen/621/assets/74387608/2772c5a3-4701-45d2-8cef-b62ddea11a3c)

**Comment by tonyghchen** [comment]
Solved at 10/30 reversion
