### ISSUE TITLE
教導模式下產生的調機程式有過多的多餘碼,產生後須自動跳到下一行+

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#44]
下圖是在N000行做教導的動作,手動移動X1到600後,按下G2
===>有問題的是:紅色部分應該是空白,程式cursor應該移到N001
![t23](https://github.com/tonyghchen/621/assets/74387608/691765e8-efd1-4afa-aedc-3586f1753aff)

**Comment by tonyghchen** [comment]
Solved at 2023/11/16 reversion
