### ISSUE TITLE
剛開機時,段數顯示和段數值不一致

### ISSUE THREAD

**Issue by fun2781** [tonyghchen/621#6]

**Comment by fun2781** [comment]
以X5為例,顯示第三段,但段數值1*1第三段
![t8](https://github.com/tonyghchen/621/assets/74387608/bb5fecd1-810d-4fd1-a1fa-51e2a16f9b99)
應該要1*100

**Comment by tonyghchen** [comment]
值有更新, 點點沒更新

**Comment by tonyghchen** [comment]
Solved at 10/25 reversion
